name: wazo-calld-queue
namespace: sboily
version: 0.0.6
author: Sylvain Boily
display_name: Queue API and events
min_wazo_version: 23.11
tags:
  - experimental
  - queue
homepage: https://github.com/sboily/wazo-calld-queue
